services:
  redis:
    image: redis:7-alpine
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend_api_service
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped

  graphql:
    build: ./graphql
    container_name: graphql_api_service
    ports:
      - "4000:4000"
    environment:
      - BACKEND_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "5173:80"
    depends_on:
      - graphql
    restart: unless-stopped

volumes:
  redis_data:
